#In case of Shader Compilation Error flutter run --enable-software-rendering and wrap widgets in scaffold
name: erims
description: Event Registeration and Information Management System

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.0+2
  google_sign_in: ^4.0.1+1
  geolocator: 5.0.1
  uuid: ^2.0.0
  image: ^2.0.7
  animator: 0.1.4
  path_provider: ^0.5.0+1
  timeago: 2.0.17
  cached_network_image:
  flutter_svg:
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.4+2
  cloud_functions: ^0.4.2+3
  firebase_auth: ^0.15.5+2
  firebase_storage: ^3.1.3
  firebase_messaging: ^6.0.12
  argon_buttons_flutter: ^1.0.2
  grouped_buttons: ^1.0.4
  beauty_textfield: ^0.0.1
  flutter_spinkit: ^4.1.2
  modal_progress_hud: ^0.1.3
  datetime_picker_formfield: ^1.0.0
  table_calendar: ^2.2.3
  dropdown_formfield: ^0.1.1
  sliding_card: ^0.1.1
  rflutter_alert: ^1.0.3
  flutter_launcher_icons: ^0.7.3
  flushbar: ^1.5.0
  flutter_email_sender: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/erims.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: APro
      fonts:
        - asset: assets/fonts/Anonymous_Pro.ttf
    - family: AProBold
      fonts:
        - asset: assets/fonts/Anonymous_Pro_B.ttf
    - family: Cantarell
      fonts:
        - asset: assets/fonts/Cantarell-Regular.ttf
    - family: CantarellO
      fonts:
         - asset: assets/fonts/Cantarell-Oblique.ttf
    - family: CantarellBO
      fonts:
         - asset: assets/fonts/Cantarell-BoldOblique.ttf
    - family: CantarellB
      fonts:
         - asset: assets/fonts/Cantarell-Bold.ttf

  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/


